### ISSUE TITLE
scheduler caught exception: can't convert nil into Float

### ISSUE THREAD

**Issue by jwl17330536** [acockburn/hadashboard#5]
Anyone else seeing this?  I've been tailing my log for an hour and 15 minutes and it has happened on six occasions.  I've always noticed it, but never have been concerned with it as everything that I've tested works!

```
scheduler caught exception:
can't convert nil into Float
/var/opt/hadashboard/jobs/homeassistant.rb:232:in `Float'
/var/opt/hadashboard/jobs/homeassistant.rb:232:in `block in <top (required)>'
/var/lib/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
/var/lib/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/var/lib/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/var/lib/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `call'
/var/lib/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'
```

**Comment by acockburn** [comment]
I checked and I have seen this too, but not for a couple of weeks.

Upon further investigation, this is caused by the weather schedule. It seems that occasionally one or the other of "weather_temperature" or "weather_apparent_temperature" is not returned correctly and the attempted conversion to Float errors out. I am not sure of the circumstances in which this happens but I think the way I am calculating wind chill may not be correct anyway. I think I will fix this by passing the weather_apparent_temperature straight through. None of the other fields require a float conversion and there haven't been any other issues so I think this will fix it.

I'll push out a fix in the next version. If that doesn't fix it let me know.

**Comment by jwl17330536** [comment]
No problem!  I don't use the weather portions, so I'm not seeing any functionality problems from this.

**Comment by acockburn** [comment]
Heh - I posted a fix anyway :)
